### ISSUE TITLE
Move semantics that need to be addressed...

### ISSUE THREAD

**Issue by JamesGaier** [Nicholas-Baron/little-lang#2]
https://github.com/Nicholas-Baron/little-lang/blob/740e0b05830e9bea0a942f91a9bab7bcea78392f/src/nodes.hpp#L16

**Comment by Nicholas-Baron** [comment]
I need to move from the temporary in the constructor as well. For pointers, this is not required as unique and shared can be initially constructed and take ownership of a raw pointer.

[Godbolt Proof](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtRkBSAJgCFufSAZ1QBXYskwgA5BwAMAQW4BmPC2QMRWANQclAYTypBBYpiYBbXdjmKF6poMFaAcqjyCAnhwDsfBTa1ArVUCYPQAfV0/W3kABxEAIwY8ZBAAoNd3DwgASh0lABEtLAZMAkwo9MDMAA9Y5ORCFzdPCBCwvJAw8Lb0HJ9ooKGtY3QQFFFQ3T1pnS4uPVQWY2IRZHL0MLmufJn9bt3ZsBkAVj0WY8qFIZ8CmyrmrIg0ZdDMz24ANhHxTu6IQTiAB0eAieQGDyGo3GaBEU30s24C1QsQ8WheKzWG22h32oPCuL0WkuZwuMiUgyCt3u1wyLWy7y8XE%2BXx%2ByD%2B%2BIBwPx4N8kKC0ImcMJ2wAsqgAG6YdFLTHrTCbJEi/EiknnS4Uh7U/y0wKM1kozDEJhEYi6ArPWVvemswHsnR83XDFXmtkgiJXeTDAUEMZC%2BF7IlIxaorQOQR4YAsBU46azF0I/Zqsme72BUwEMQsLQAKgICHcqap3juOq9dKyBtiRpNJHNEH1zNtvwdlO9CaKdvdkU1TqhvphkxFSPFUrDjkj0cV82VEVVp3V5LbwwzWdz%2BcLvfLgW1MSGAD9GbktCxULUJLEpo7t8NBbCA4j5gVMCtUB4Y0q43i51%2BicmNcuu7UluNj2I4Wiiq2DyMiePbRPESQpGkToAPQoVoIZ4C%2BWj5tKdo4Zg5ixMELBELBDyig2NpNsybJ/CwPR2ryfAlvcrEgXYzDgaKkEQk6MEMZ6CENMhN5oRBkrYQAZsQqDmGyBFESRZGCU6PFUZWNHfExWhdAxAIDiA5iSVy7LMUB7HRKBXFOAAYlB/H0uRW7CUhDy2RpHxaXRumwQZfpSSQADuTDEOg0xYOoBAeNWpn9Eo2BxeZrH%2BJZNLyO05hMKouR8XuxbLkMMHlMYAy0MBhVBJBqBBdGZq%2BIKxlShAJUEP0aVOkBTp3kOv4jIZmAsOgDCelq15po8ngEaVvhcBV/KBDxWg1XVAyNSZrXtXcW43Cl%2BWBD1wp9YKg3DaNnXjWmxUvgQAxKPNfZBPZK1GmthlNZgLU3VtRY7ntbEFFIOSMNIJxSKQLDSLI4OoNIMy8PwIyiOI0rKLQ4MEFDQPAwA1iAAAsACcQKyLIJzeCcny0PjAAcVNKEoINSPj4PmHQpMQ1jpCw1I4OCCAsikJjUjQ8DcCwDAiATEReClGQFCWjLcsoMwbDhCYIgsDjpBSbL5TEPzEAJFzCSqKFHjSOjpBoOY5iDQQADyLAMBbIvg1gWVsKUXP4KY6x4FK/Nu6QtSYMgcKSMHISYAwXPJAkxrEB4ixYJbGPEHgbNSOjwOq%2Bw/D8IweAJPzkDAyiBCGMs0gALSjOanAI7wtDeFoNcAOpMAwDBt%2B3tQmEwbcO3zyMSHQueg%2BDkPBzzNR0zXnz4%2BiedaC1qxa3kEC4IQJBzEo9AYXJsSy0ae%2B0Hk8N8LwGNYzkuMgCcshAoThP41w%2BNKDTJy0J/nzeFwTMWakDZo/TmM9pB8wFkLW%2BpBxZS0mPEAg5BKA22PsregCod7EDoKQIKxpYhpwnlIMGYDobc2kGjLQQVCAIC0HPT4C8l72DYKvDWG8b5uzvqQBAZgsDYNyIA1mD9BbTzITzSBgthai3vo/Z%2Br936f2/r/f%2BTMlBTy5uI6BnCiFcCEbQDmoiYYQK0dI0gUoDZVwJkAA%3D%3D%3D)
